### ISSUE TITLE
Support for stylelint 16

### ISSUE THREAD

**Issue by d-koppenhagen** [ota-meshi/stylelint-config-recommended-vue#63]
Currently Stylelint fails when trying to update to v16 with the following error:

```
> npx stylelint "src/**/*.{vue,scss}"

TypeError: Cannot read properties of undefined (reading 'rejected')
    at Object.<anonymous> (/Users/dev/project/node_modules/stylelint-scss/src/rules/comment-no-empty/index.js:12:42)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/Users/dev/project/curbee/node_modules/stylelint-scss/src/rules/index.js:31:23)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
```

This is probably caused by some breaking changes described in the docs migration guide:
https://github.com/stylelint/stylelint/blob/main/docs/migration-guide/to-16.md

Probably this depends also on updating `stylelint-config-standard-scss` where an equivalent issue was opened:
https://github.com/stylelint-scss/stylelint-config-standard-scss/issues/145

**Comment by ota-meshi** [comment]
I have added a test case and it is working fine #65. Could you please provide a repository to reproduce your problem?

**Comment by d-koppenhagen** [comment]
Okay, You checked it just after the release of `stylelint-config-standard-scss@^12.0.0`. With the latest update of `stylelint-config-standard-scss` it works indeed. I will close this issue :)
