### ISSUE TITLE
LRU is not a constructor

### ISSUE THREAD

**Issue by thisVioletHydra** [ota-meshi/stylelint-config-recommended-vue#77]
i got this bug🐞 if i use  latest `Bun`

install packages with `pnpm` -- all good 🤔

The extension broke after the last update or stylelint or the extension itself
vscode gets mad at stylelint-config-recommended-vue

```q
Error - 2:26:07 PM] (node:30388) [stylelint:002] DeprecationWarning: The CommonJS Node.js API is deprecated.
See https://stylelint.io/migration-guide/to-16
[Error - 2:26:07 PM] [language-server] Error running lint | uri: "file:///c%3A/generateStyles/layer-theme/theme/pipe.postcss" 
error: {
  "filepath":"C:\\www\\playground\\node_modules\\stylelint-config-recommended-vue\\lib\\index.js",
  "name":"TypeError","message":"LRU is not a constructor",
  "stack":"TypeError: LRU is not a constructor\n    
  at Object.<anonymous> (C:\\www\\playground\\node_modules\\stylelint-config-recommended-vue\\node_modules\\semver\\classes\\range.js:202:15)\n    
  at Module._compile (node:internal/modules/cjs/loader:1373:14)\n    
  at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)\n    
  at Module.load (node:internal/modules/cjs/loader:1215:32)\n    
  at Module._load (node:internal/modules/cjs/loader:1031:12)\n    
  at c._load (node:electron/js2c/node_init:2:13801)\n    
  at Module.require (node:internal/modules/cjs/loader:1240:19)\n   
  at require (node:internal/modules/helpers:179:18)\n    
  at Object.<anonymous> (C:\\www\\playground\\node_modules\\stylelint-config-recommended-vue\\node_modules\\semver\\classes\\comparator.js:141:15)\n    
  at Module._compile (node:internal/modules/cjs/loader:1373:14)"
}
```

**Comment by ota-meshi** [comment]
Can you share a repository where the issue can be reproduced?
